<?php
/**
 * AdTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Ebay\Sell\Recommendation
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Recommendation API
 *
 * The Recommendation API returns information that sellers can use to optimize the configuration of their listings on eBay. Currently, the API contains a single method, findListingRecommendations. This method provides information that sellers can use to configure Promoted Listings ad campaigns to maximize the visibility of their items in the eBay marketplace.
 *
 * The version of the OpenAPI document: 1.1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Ebay\Sell\Recommendation\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AdTest Class Doc Comment
 *
 * @category    Class
 * @description A complex type that contains recommendations and information on how to configure Promoted Listings ad campaigns.
 * @package     Ebay\Sell\Recommendation
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AdTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Ad"
     */
    public function testAd()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bid_percentages"
     */
    public function testPropertyBidPercentages()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "promote_with_ad"
     */
    public function testPropertyPromoteWithAd()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
